### ISSUE TITLE
Ignore certain protocols (such as mailto: and tel:)

### ISSUE THREAD

**Issue by luksak** [harlan-zw/nuxt-link-checker#16]
### Clear and concise description of the problem

Currently `nuxt-link-checker` checks all links. We should exclude certain common (such as `mailto: `and `tel:`) protocols from checking, since we are unable to verify them and they currently fail.

### Suggested solution

exclude `mailto:` and `tel:` links

**Comment by harlan-zw** [comment]
Hi, these should be ignored as of the latest version. Would you mind trying out 2.1.7?
