### ISSUE TITLE
External links seem to be broken in latest version

### ISSUE THREAD

**Issue by ennioVisco** [harlan-zw/nuxt-link-checker#18]
### Describe the bug

Not sure why, but I'm getting 404 on latest update for external links, it wasn't happening before:
<img width="903" alt="image" src="https://github.com/harlan-zw/nuxt-link-checker/assets/740025/3b59e509-0ee3-4e58-aad0-9533c52b08d1">

Could it be a regression from latest changes?

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Darwin
- Node Version:     v18.16.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.6.12
- Builder:          -
- User Config:      experimental, runtimeConfig, typescript, css, modules, site, nitro, alias, vite
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.4, nuxt-parallel-limit@0.0.3, @nuxtjs/google-fonts@3.0.2, @dargmuesli/nuxt-cookie-control@6.2.0, nuxt-icon@0.5.0, @vueuse/nuxt@10.4.1, @nuxt/devtools@0.8.2, nuxt-vitest@0.10.4, @nuxtseo/module@2.0.0-beta.26
- Build Modules:    -
------------------------------
```

**Comment by toniengelhardt** [comment]
Same issue

**Comment by modbender** [comment]
@harlan-zw I'm getting the same problem, I'm having share buttons on my site, and the links are being flagged
![image](https://github.com/harlan-zw/nuxt-link-checker/assets/25717245/25e8b81f-e0b7-4ebe-af69-026d1a065070)

**Comment by modbender** [comment]
The only solution I see is to add something like 
```js
  linkChecker: {
    excludeExternalLinks: true,
  },
```

let `excludeExternalLinks` default value be `true`.

Main reasons is that:
- When probing external links you might be determined as a bot and end up getting some kind of error.
- Changes in external link page, redirects, malware downloads.
- Possible for the page to be behind authentication or paywall which might end in a HTTP 401 or 403 error.
- Other error codes like HTTP 429 and more.

**Comment by harlan-zw** [comment]
Checking external links I decided was too buggy to handle from the module. I've disabled by default in a more recent version.

I may add it back as a button you can press in the devtools to scan all external links
