### ISSUE TITLE
feat: bundle requests

### ISSUE THREAD

**Issue by dargmuesli** [harlan-zw/nuxt-link-checker#21]
### Clear and concise description of the problem

Currently, each link triggers a separate http request, I think.
This easily triggers `nuxt-security`'s rate limiting when developing pages with more than a few links on them.

### Suggested solution

If possible, it would be cool if there would be a single request for all links discovered in a single run to save on some network overhead.

### Alternative

Disable rate `nuxt-security`'s rate limited for development or increase its limits.

### Additional context

The network overhead argument is more of theoretical nature as far as I see as link checking is run in development or at build time only. Please correct me if the issue could indeed be practically relevant.

**Comment by harlan-zw** [comment]
Agreed! This module needs some work around optimizing the link checking (ideally it would batch process via nitro internal fetch's).

**Comment by harlan-zw** [comment]
In `3.0.0-rc.3`, it will batch process 50 links at a time. Also the API endpoint is at `/__link-checker__/inspect` now, the rate limiter should probably ignore these internal URLs.
