### ISSUE TITLE
excludeLinks pattern

### ISSUE THREAD

**Issue by fvena-portfolio** [harlan-zw/nuxt-link-checker#28]
### Details

On my website, I have a list of employees along with links to their social media profiles (LinkedIn, Twitter, Instagram, etc.). If I individually add each link to the `excludeLinks` property in the configuration, it works as expected. However, this approach seems impractical when dealing with 40 social media links. 

I attempted to add `absolute-site-urls` to the `skipInspections` property in the configuration, but it triggered a warning. 

I'm interested in knowing if the `excludeLinks` property could support a pattern matching format like `https://www.linkedin.com/**` to simplify the process.

**Comment by harlan-zw** [comment]
Hey, I'd recommend using the v3 RC. It disables absolute URL scanning by default.

The exclude should support globs so not sure what's going on there :thinking: A reproduction would be helpful if v3 doesn't solve your issues.
