### ISSUE TITLE
URI-encoded links to static pages with special characters result in erroneous 404s

### ISSUE THREAD

**Issue by tydeu** [harlan-zw/nuxt-link-checker#30]
### Describe the bug

The `no-error-response` inspection will note a 404 response for links to generated static pages with special characters that have been URI encoded. For example, If a page links to `/foo%20bar` with and there is the appropriately generated `foo bar.html`, the link checker will still complain about a 404.

Debugging this error revealed that the problem is that the responses cache does not account for potential URI encoding of generated routes in links. That is, these two lines expect a route and its link to match exactly:

https://github.com/harlan-zw/nuxt-link-checker/blob/8ea107a012ab2ede587e53d1c6967355bd1267f4/src/prerender.ts#L50

https://github.com/harlan-zw/nuxt-link-checker/blob/8ea107a012ab2ede587e53d1c6967355bd1267f4/src/runtime/pure/crawl.ts#L9

I think the appropriate solution here is to index into `responses` using `decodeURI(link)`.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-cdcjya

Use `npm run generate` in a new terminal to see the error.

**Comment by harlan-zw** [comment]
I've tried to replicate this so I can make sure it's fixed properly but had some issues. Would you be able to make a reproduction using https://stackblitz.com/edit/nuxt-starter-qtaq7x?file=pages%2Findex.vue as a starter :pray: ?

**Comment by tydeu** [comment]
@harlan-zw I have a repdouction at https://stackblitz.com/edit/nuxt-starter-cdcjya. Use `npm run generate` in a new terminal to see the error.

**Comment by harlan-zw** [comment]
Thanks for the reproduction, it appears to be fixed with 3.0.0-rc.9.
