### ISSUE TITLE
feat: config for report output destination and other suggestions

### ISSUE THREAD

**Issue by remihuigen** [harlan-zw/nuxt-link-checker#38]
### 🆒 Your use case

So I was fiddling around with generating link reports. These might come in handy for our CMS editors to check for broken links, since my prerender config contains ``failOnError: false`` (i dont want it to fail for every 404)

When running a build locally, the link-checker-report.html (or .md) file is generated in the ./.output folder. But if i want to access it from my Nuxt App directly, it would make more sense to have it in ./.output/public/link-checker-report/index.html

Also, when deploying to Netlify, I'm getting ``Nuxt Link Checker HTML report written to .netlify/functions-internal/link-checker-report.html``. Which is weird, since all other files are outputted in a dist folder conform the [nitro preset for netlify](https://nitro.unjs.io/deploy/providers/netlify). This might be an upstream bug though, since [this seems to be okay](https://github.com/harlan-zw/nuxt-link-checker/blob/18a3936af5e9f587328366a11ca6624bb440f109/src/prerender.ts#L173)

Lastly, for the reports to be actually useful, the UI would need an upgrade. At this point (with 500+ prerendered routes) it' just an endless list

### 🆕 The solution you'd like

First, I would suggest adding a new config prop called ``outputDir``, which accepts a function with a single argument, the current nitro config. This would give control over the output behavior of reports.

```
linkChecker: {
    failOnError: process.env.FAIL_BUILD_ON_ERROR === 'true',
    report: {
      html: true,
      markdown: false,
      outputDir: (nitro) => resolve(nitro.options.output.dir, 'public', 'link-checker-report', 'index') // where index is the file name
    }
  }
```

Secondly, I'd like to add a third output type ``json``, which would write the [``allReports``](https://github.com/harlan-zw/nuxt-link-checker/blob/18a3936af5e9f587328366a11ca6624bb440f109/src/prerender.ts#L64C13-L64C23) into a json file. This would allow us to build a custom UI in our nuxt app for the report data

```
linkChecker: {
    failOnError: process.env.FAIL_BUILD_ON_ERROR === 'true',
    report: {
      html: false,
      markdown: false,
      json: true,
      outputDir: (nitro) => resolve(nitro.options.output.dir, 'public', 'link-checker-report', 'index') // where index is the file name
    }
  }
```

**Comment by harlan-zw** [comment]
Hey, I've released [v3.1.0](https://github.com/harlan-zw/nuxt-link-checker/releases/tag/v3.1.0) which may solve this for you.

While the report should be easier to navigate with less data, I'm open to improving the UI but I don't have capacity at the moment. If you want to make a new issue with any ideas for it, that would be great.

By the way, this feature was originally built to have the reports displayed as part of your CI. For example, you can use the [comment GitHub action](https://github.com/GrantBirki/comment) to add the link report to any production PRs.

```yml
    - name: Sync links
      uses: GrantBirki/comment@v2
      with:
        file: .output/link-checker-report.md
```

Will close for now but let me know if you have any feedback.

**Comment by remihuigen** [comment]
3.1.0 is looking! This was exactly my suggestion 😀 will give it a go tomorrow.

As for the UI, i'll let you know if I have built something for it. The project I'm currently working on is using Nuxt UI, so that wouldake it easier to refactor for usage in this nuxt module.

**Comment by remihuigen** [comment]
Hi Harlan,

Built a quick UI component based on [this example](https://github.com/nuxt/ui/blob/dev/docs/components/content/examples/TableExampleAdvanced.vue). 

for a demo, see [https://dev.traineesinonderwijs.nl/link-report/](https://dev.traineesinonderwijs.nl/link-report/)

It's built with Nuxt UI, into a single component ``<RouteList :data="data" />`` where the data prop is the generated json report, so it should be fairly simple to integrate into your module.

If you'd like I could make a PR

And more more thing: why filter for ``reportsWithContent`` in 
```
const reportsWithContent = allReports.filter(({ reports }) => reports.some(r => r.error?.length || r.warning?.length))
```

I actually also want reports without errors and warnings, so i have a complete list of all (prerendered) routes!

PS. Is the type of ``warning`` identical to ``error``? Could not find a type declaration in the src

**Comment by harlan-zw** [comment]
This looks great :+1: There is complexity involved around this though, we'd need a separate nuxt app just to render the list to HTML.

> I actually also want reports without errors and warnings, so i have a complete list of all (prerendered) routes!

I'd imagine most people don't as they can check their sitemap if they need a URL list. I will consider adding this back if there is some useful data for each route (i.e the internal / external link counts).

> PS. Is the type of warning identical to error? Could not find a type declaration in the src

Yes
