### ISSUE TITLE
fix: Link checker during build does not have access to internet

### ISSUE THREAD

**Issue by strife-cloud** [harlan-zw/nuxt-link-checker#39]
### 🐛 The bug

I'm using nuxt 3 and during "nuxt generate", nuxt-link-checker try to his job but I've got the following errors 
![bug](https://github.com/user-attachments/assets/a9b731b2-eba7-4cb7-94f5-2fc71a2fb95d)

And it feels like because it doesn't have access to internet during the check, because the links in the screen are valids.

### 🛠️ To reproduce

https://nuxtseo.com/link-checker/getting-started/stackblitz

### 🌈 Expected behavior

It should return no error on valid URLs

**Comment by harlan-zw** [comment]
Hi @strife-cloud, can you confirm which version you're using?

Since v3 it should not fetch remote URLs by default, it should also test for internet before using this feature.
