### ISSUE TITLE
Support app.baseURL

### ISSUE THREAD

**Issue by P4sca1** [harlan-zw/nuxt-link-checker#41]
### 🆒 Your use case

When building my app with `NUXT_APP_BASE_URL=/some-prefix/ pnpm generate`, it would be great if `nuxt-link-checker` would still be able to resolve links to files in the `public/` directory.

### 🆕 The solution you'd like

Maybe stripping `app.baseUrl` before checking the `public/` directory could work.

### 🔍 Alternatives you've considered

Build without baseURL to check for errors, then build again with base URL, ignoring any error.

**Comment by harlan-zw** [comment]
Hi, are you able to make a reproduction for this? I tried to replicate without issue.

https://stackblitz.com/edit/nuxt-starter-7vnhkz?file=nuxt.config.ts
