### ISSUE TITLE
Use the redirect file to avoid 404

### ISSUE THREAD

**Issue by Barbapapazes** [harlan-zw/nuxt-link-checker#9]
### Clear and concise description of the problem

This tool can detect 404 even when there is a redirect file that redirect the link to somewhere else.

### Suggested solution

Read the redirect file to mark these link as redirected instead of 404.

We could go further to test if the redirect is a 404.

A redirect file like this https://docs.netlify.com/routing/redirects/

**Comment by Barbapapazes** [comment]
And thanks for your amazing works 🙏

**Comment by harlan-zw** [comment]
Great idea, thanks :)

**Comment by harlan-zw** [comment]
This should be solved in v2, although this may be blocking it https://github.com/harlan-zw/nuxt-link-checker/issues/13
